# Generated by Django 5.1 on 2024-08-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='type_of_link',
            field=models.CharField(choices=[('Geo', 'Geographical Elevation visualization'), ('3d', '3D scatter plot visualization')], default='3d', max_length=100),
        ),
    ]
